version: '3.1'

services:
    db:
        image: postgres:12.2
        ports:
            - "5400:5432"
        restart: always
        environment:
            POSTGRES_DB: DBplay
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: 123
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    admin:
        image: adminer
        restart: always
        depends_on:
            - db
        ports:
            - "5401:8080"
